name: ğŸ” SSL Check

on:
  schedule:
    - cron: "0 15 * * *"

env:
  DOMAIN: https://arash-hatami.ir

jobs:
  SSL:
    runs-on: ubuntu-latest
    name: Check domain

    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: codex-team/action-check-domain@v1
        with:
          url: ${{ env.DOMAIN }}

      - name: Show results
        run: echo 'SSL cert has ${{ steps.check-domain.outputs.ssl-expire-days-left }} days left'
        if: ${{ steps.check-domain.outputs.ssl-expire-days-left }}

      - name: Create an issue if paid till number is below limit
        if: ${{ steps.check-domain.outputs.paid-till-days-left && steps.check-domain.outputs.paid-till-days-left < 10 }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: âš ï¸ ${{ env.DOMAIN }} â€” registry expiries in ${{ steps.check-domain.outputs.paid-till-days-left }} days
          body: "Paid till: `${{ steps.check-domain.outputs.paid-till-date }}`"

      - name: Create an issue if SSL lifespan days number is below limit
        if: ${{ steps.check-domain.outputs.ssl-expire-days-left && steps.check-domain.outputs.ssl-expire-days-left < 10 }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ğŸ§¨ ${{ env.DOMAIN }} â€” SSL cert expires in ${{ steps.check-domain.outputs.ssl-expire-days-left }} days
          body: "Valid till: `${{ steps.check-domain.outputs.ssl-expire-date }}`"
